---

services:
  hapi:
    image: hapiproject/hapi:v7.0.3
    container_name: hapi
    ports:
      - 8888:8080
    volumes:
      - ./application.yaml:/app/config/application.yaml
    restart: always
